let talk_alone = [
    "Hmm, I wonder how long this will take.",
    "Oh, there's that weird humming sound again.",
    "I should have taken the stairs… nah.",
    "Maybe I should check my phone while I wait.",
    "I always forget how slow this elevator is.",
    "That's a nice little ding sound when it arrives.",
    "Maybe I should count how long it takes to get here.",
    "Did I press the button? Oh yeah, I did.",
    "I love how shiny these elevator doors are.",
    "This lobby always smells nice.",
    "I wonder if I can beat my own record to my floor today.",
    "Why do I always get here right after it leaves?",
    "I should take a deep breath and relax.",
    "I swear this elevator likes to take its time.",
    "Maybe this is a sign I should slow down and be patient.",
    "I could do a little stretch while I wait.",
    "I wonder if elevators have personalities.",
    "This is a great chance to just stand still for a moment.",
    "Ooh, I can see my reflection in the doors!",
    "I should enjoy these few seconds of quiet.",
    "I bet if I hit the button again, it won't come any faster… but I kinda want to.",
    "This building really has a nice design.",
    "I think I heard it moving!",
    "Why does waiting for an elevator feel longer than it actually is?",
    "I should make a playlist for \"waiting for things.\"",
    "Why does it always feel longer when you're watching the doors?",
    "I bet if I looked away, it would show up faster.",
    "Maybe I should check my phone… nope, still waiting.",
    "I wonder how many people have waited right here today.",
    "Oh, the button is already lit—someone else is waiting too.",
    "If I had taken the stairs, I'd probably be halfway there by now.",
    "Nope, I'm committed to the elevator now.",
    "Did I press the button hard enough?",
    "I think I can hear it moving.",
    "Maybe I should time this and see how long it actually takes.",
    "I bet it just stopped on every single floor before mine.",
    "This would be the perfect time for a deep breath.",
    "I should just enjoy this tiny pause in my day.",
    "If patience is a virtue, I'm getting a workout right now.",
    "I wonder what people did before elevators… oh right, stairs.",
    "I should stretch my arms while I wait.",
    "It would be funny if it arrived the second I turned around.",
    "Wouldn't it be weird if it just never came?",
    "I bet I'll forget what I was thinking about as soon as I step inside.",
    "I feel like I always catch the slowest elevator.",
    "At least I'm not in a rush this time.",
    "What if I just took the stairs for fun? Nah.",
    "I wonder how long it's been since this elevator was installed.",
    "This would be a good moment for some background music.",
    "I wonder if pressing the button twice actually does anything.",
    "Okay, now it's just taking its sweet time.",
    "I hope I get a solo ride.",
    "Elevators always feel faster when you're with someone else.",
    "I should probably stand back so I don't get surprised when the doors open.",
    "Maybe I'll start a new habit—thinking of one fun fact while I wait.",
    "If I were an elevator, I'd be the fast one.",
    "Wouldn't it be wild if it opened and there was a dog inside?",
    "I always wonder what's behind those little maintenance panels.",
    "This would be a good time for a quick mindfulness exercise.",
    "I wonder how many steps I'd have to take to my floor.",
    "Ooh, I like the reflection in these doors.",
    "Maybe if I act distracted, it'll come faster.",
    "Alright, elevator, I believe in you.",
    "This would be a great spot for a tiny bench.",
    "Do elevators get tired? No, that's silly.",
    "I should start tracking my average wait times.",
    "I wonder if I could guess the exact second it arrives.",
    "This is a nice moment to just be still.",
    "I could hum a little tune, but that might be weird.",
    "Oh, I think I heard a ding!",
    "Okay, elevator, let's do this.",
    "Alright, suspense is building… any second now.",
    "It's funny how waiting feels like time slows down.",
    "I could take a power nap if it took much longer.",
    "I bet the person who designed this elevator didn't expect people to think this much while waiting.",
    "Should I pace a little or just stand still?",
    "I feel like I should be doing something productive right now.",
    "Maybe I'll count how many tiles are on the floor.",
    "Wouldn't it be funny if someone inside was doing the same thing—waiting to go down?",
    "At least this is better than standing in line somewhere.",
    "I should have grabbed a snack first.",
    "I should start carrying a book for moments like this.",
    "Maybe I'll try to guess who'll get off on which floor.",
    "I could pretend I'm in an elevator scene from a movie.",
    "This elevator is really making me appreciate patience today.",
    "I feel like I should be stretching or something.",
    "I wonder if anyone has ever danced while waiting for an elevator.",
    "I swear it was faster the last time I was here.",
    "Wouldn't it be weird if the doors just opened and no one was inside?",
    "Oh, I thought I heard something, but nope.",
    "Elevator, I'm rooting for you!",
    "I could probably solve a whole math problem before it gets here.",
    "Maybe I should start a blog about waiting for elevators.",
    "If I took the stairs, I'd have my cardio for the day.",
    "I wonder if anyone's ever counted how many times it moves up and down daily.",
    "Okay, I'm officially invested in how long this will take.",
    "The anticipation makes it more exciting… kind of.",
    "Maybe I should manifest the elevator arriving now… nope, didn't work.",
    "If I turn around three times, will it arrive?",
    "Alright, I'm giving it ten more seconds in my head.",
    "What if it just never came? I guess I'd have to live here now.",
    "I could do a little dance while I wait… but maybe not.",
    "I should just embrace the waiting process.",
    "If I close my eyes and open them, maybe it'll be here.",
    "I bet it's stopping at every floor before mine.",
    "This is a good moment to check my posture.",
    "I should start a game where I count how long it takes every time.",
    "I bet it'll come just when I get distracted.",
    "It's like watching a pot boil—takes forever.",
    "Alright, let's practice patience.",
    "Maybe I'll do a little stretch while I wait.",
    "I should appreciate this tiny pause in my day.",
    "I wonder what materials they use to make elevator buttons.",
    "If I took the stairs, would I regret it halfway up?",
    "I hope I don't get an awkwardly full ride.",
    "What if it arrives and is completely empty? That'd be nice.",
    "I should savor the quiet while I can.",
    "Maybe I'll try to predict which floor it's coming from.",
    "This is a nice excuse to just stand still for a second.",
    "I wonder how many floors this elevator serves.",
    "I think I hear it! Or maybe that was just a noise from the hallway.",
    "It's probably debating whether to come here or not.",
    "This wait is giving me way too much time to think.",
    "Alright, elevator, let's wrap this up.",
    "Finally! Show time.",
]

let talk_with_company = [
    "Busy day today?",
    "Looks like we got here at the same time.",
    "I think this elevator has its own schedule.",
    "Always feels like forever, huh?",
    "I swear it was faster yesterday.",
    "At least we're not the only ones waiting.",
    "I think the universe just likes to test my patience.",
    "You'd think with all this technology, we'd have instant elevators by now.",
    "I always wonder what's happening inside while it moves.",
    "Oh, there it is! Perfect timing.",
    "Guess we just missed it, huh?",
    "You can never tell if it's coming up or down until the last second.",
    "This is one of those \"hurry up and wait\" moments.",
    "I always press the button even if it's already lit. Just in case.",
    "Elevator roulette—let's see if it's empty or packed!",
    "It's funny how we all go quiet when it arrives.",
    "Ever notice how people avoid eye contact when waiting?",
    "It's nice to have a second to just pause, though.",
    "I think this is the longest I've ever waited.",
    "I swear this building has a ghost elevator—sometimes it just skips floors.",
    "Well, at least we're getting a little break before the next thing.",
    "This is a good moment for a deep breath.",
    "Wouldn't it be funny if it opened and it was just a broom closet?",
    "Nothing like a little anticipation to start the day.",
    "Okay, let's see how full this one is.",
    "Looks like we got here at the same time—good timing!",
    "I think this elevator likes to take its time.",
    "You ever notice how it always seems slower when you're watching it?",
    "I swear it was faster yesterday.",
    "I think this one has a mind of its own.",
    "At least we're not the only ones waiting.",
    "I always forget how long this can take.",
    "I bet the second we start talking, it'll show up.",
    "Did you see that? I thought the doors twitched for a second.",
    "I feel like it's stopping at every floor on the way down.",
    "I think pressing the button again makes me feel better, even if it does nothing.",
    "How's your day going so far?",
    "I should have timed this wait—I bet it's longer than usual.",
    "I always wonder what's happening inside that slows it down.",
    "I feel like we've been here forever… but it's probably been a minute.",
    "I think the elevator is playing hard to get.",
    "Isn't it funny how some days it's instant, and other days it's like this?",
    "I should start taking bets on how long it takes.",
    "This would be the perfect time for some elevator music.",
    "So, do we think it's stuck, or just being dramatic?",
    "I feel like I just missed one, and now I'm paying for it.",
    "Every time I consider taking the stairs, it suddenly arrives.",
    "What floor are you heading to?",
    "Wouldn't it be funny if the power went out right now? Just kidding.",
    "At least we're getting a moment to slow down for once.",
    "I always forget how quiet it is while waiting for an elevator.",
    "Watch, the doors are going to open right when I check my phone.",
    "You ever get in and suddenly forget what floor you're going to?",
    "I wonder if we'd get there faster if we just walked.",
    "Hopefully, it's not too crowded when it gets here.",
    "I feel like the universe is testing my patience right now.",
    "I keep expecting to hear the ding, but nope.",
    "I should start rating elevators on speed and reliability.",
    "Let's hope we don't stop on every floor on the way up.",
    "Wouldn't it be funny if the doors opened and it was empty, but we still had to wait?",
    "I bet it's full of people trying to squeeze in.",
    "Maybe we should start chanting for it to arrive.",
    "You ever feel like you summoned the elevator when it finally arrives?",
    "I should have grabbed a coffee while waiting.",
    "I feel like elevators have their own secret schedules.",
    "Do you think talking about it is making it take longer?",
    "I always feel bad if I get in first and someone is running for it.",
    "Ever get in an elevator and forget to press the button? Just me?",
    "Well, at least we're getting some extra standing practice today.",
    "I wonder if the people inside are wondering why we're still waiting.",
    "Let's just agree that we're on an adventure now.",
    "Maybe it's one of those days where taking the stairs would've been smarter.",
    "If this were a movie, something dramatic would definitely happen right now.",
    "I think this is the universe reminding me to slow down.",
    "Finally! I was starting to think it retired for the day.",
]

let talk_on_the_elevator = [
    "Ah, perfect timing!",
    "There we go—finally moving.",
    "Which floor are you headed to?",
    "This one is surprisingly fast.",
    "Nice, a quiet ride today.",
    "Nothing like a smooth elevator ride.",
    "This elevator is like a little break from everything.",
    "I love how clean this one is.",
    "Well, that was a lucky catch.",
    "We made it before the doors closed—nice!",
    "Going up or down? Oh, good—we're headed the same way.",
    "Always fun when it stops at every floor, huh?",
    "This is my favorite elevator in the building—smooth ride.",
    "I always appreciate when the doors don't try to close on me.",
    "I swear, elevator music used to be a thing. What happened?",
    "Nice, no weird noises this time.",
    "Let's see if we get an express ride or if it stops at every floor.",
    "It's funny how elevators feel faster when you're not in a hurry.",
    "Ever think about how many people have stood in this exact spot?",
    "I feel like every elevator has its own personality.",
    "This is a nice moment to just be still.",
    "I always like looking at the floor numbers change.",
    "I should enjoy this moment before the next task of the day.",
    "The little ding is always satisfying.",
    "Alright, this is my stop—have a great day!",
    "I really like the design of this lobby.",
    "The lighting in here is surprisingly nice!",
    "Whoever picked this carpet had good taste.",
    "These mirrors are oddly flattering.",
    "I feel like this elevator could be in a fancy movie scene.",
    "This is my favorite elevator—never lets me down!",
    "I'm pretty sure this elevator knows when I'm running late.",
    "It's nice when you get an empty ride.",
    "I feel like an elevator is the one place where everyone has the same goal—just get to the right floor.",
    "This is the smoothest ride I've had all day.",
    "I like the little breeze you get when the doors open.",
    "Ah, the classic elevator dance—shuffling so we all fit.",
    "At least we're not stuck in an elevator like in the movies.",
    "I should start a journal of interesting elevator moments.",
    "I wonder if elevator designers ever think about how much people appreciate their work.",
    "Hope the rest of your day goes well!",
    "Nothing like a quick break between floors.",
    "Small joys—catching an elevator just in time!",
    "Enjoy your stop!",
    "We should invent an elevator game to make waiting more fun.",
    "The first elevator ride of the day always sets the tone.",
    "It's always fun when two people press the button at the same time.",
    "I think this elevator has the best timing today.",
    "There's something peaceful about an elevator ride.",
    "Here's to smooth rides and short waits!",
]

export {talk_alone, talk_with_company, talk_on_the_elevator }